camps/1506/rails-crud-livecode/config/routes.rb
Rails.application.routes.draw do
  resources :pets
end

camps/1506/rails-crud-livecode/app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["dog", "cat", "rabbit", "snake", "turtle"].freeze

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

camps/1506/rails-crud-livecode/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    # do something else with the pet...
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

camps/1506/rails-crud-livecode/app/helpers/pets_helper.rb
module PetsHelper
end

camps/1506/rails-crud-livecode/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

camps/1506/rails-crud-livecode/app/views/pets/_form.html.erb
<%= form_with model: pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :species %>
  <%= f.select :species, in: Pet::SPECIES %>
  <%= f.label :found_on %>
  <%= f.date_field :found_on %>
  <%= f.submit %>
<% end %>

camps/1506/rails-crud-livecode/app/views/pets/edit.html.erb
<%= render "form", pet: @pet %>

camps/1506/rails-crud-livecode/app/views/pets/index.html.erb
<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "Add a new pet", new_pet_path %>

camps/1506/rails-crud-livecode/app/views/pets/new.html.erb
<%= render "form", pet: @pet %>

camps/1506/rails-crud-livecode/app/views/pets/show.html.erb
<h2><%= @pet.name %></h2>
<p>Species: <%= @pet.species.capitalize %></p>
<p>Address: <%= @pet.address %></p>
<p>Found on: <%= @pet.found_on %></p>

<hr>

<p><%= link_to "Edit this pet", edit_pet_path(@pet) %></p>
<p><%= link_to "Delete this pet", pet_path(@pet), data: { turbo_method: "DELETE", confirm: "Are you sure?" } %></p>