camps/1506/gardens-on-rails/config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#index'
  
  resources :gardens, only: [:index, :show] do
    resources :plants, only: [:create, :destroy]
  end
end

camps/1506/gardens-on-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

camps/1506/gardens-on-rails/app/models/garden.rb
class Garden < ApplicationRecord
  # Relationships
  has_many :plants

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

camps/1506/gardens-on-rails/app/models/plant.rb
class Plant < ApplicationRecord
  # Relationships
  belongs_to :garden

  # Validations
  validates :name, presence: true
  validates :image_url, presence: true
end

camps/1506/gardens-on-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

camps/1506/gardens-on-rails/app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[show]
  
  def index
    @gardens = Garden.all
  end

  def show
    @plant = Plant.new
  end

  private

  def set_garden
    @garden = Garden.find(params[:id])
  end
end

camps/1506/gardens-on-rails/app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    # 1. Initialize a new plant with the params coming from the form
    @plant = Plant.new(plant_params)
    # 2. Find the garden using the garden_id param coming from the url
    @garden = Garden.find(params[:garden_id])
    # 3. Associate the plant to the garden
    @plant.garden = @garden
    # 4. Save the plant
    @plant.save

    # Redirect to the garden show page
    redirect_to garden_path(@garden)
  end

  def destroy
    # 1. Find the plant using the :id param coming from the url
    @plant = Plant.find(params[:id])
    # 2. Destroy the plant
    @plant.destroy

    # Redirect to the garden show page
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

camps/1506/gardens-on-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

camps/1506/gardens-on-rails/app/helpers/gardens_helper.rb
module GardensHelper
end

camps/1506/gardens-on-rails/app/helpers/plants_helper.rb
module PlantsHelper
end

camps/1506/gardens-on-rails/app/views/gardens/_garden.html.erb
<div id="<%= dom_id garden %>">
  <p>
    <strong>Name:</strong>
    <%= garden.name %>
  </p>
</div>

camps/1506/gardens-on-rails/app/views/gardens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gardens</h1>

<div id="gardens">
  <% @gardens.each do |garden| %>
    <%= render garden %>
    <p>
      <%= link_to "Show this garden", garden %>
    </p>
  <% end %>
</div>

camps/1506/gardens-on-rails/app/views/gardens/show.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<!-- Plants grid -->
<div class="cards my-3">
  <% @garden.plants.each do |plant| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= plant.image_url %>')">
      <%= plant.name %>
      <%= link_to "+", garden_plant_path(plant), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "card-remove-link" %>
    </div>
  <% end %>
</div>

<!-- Plants form -->
<div class="container my-3">
  <div class="row justify-content-center">
    <div class="col-4">
      <h4>Add a plant:</h4>
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "Insert an image URL" %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

camps/1506/gardens-on-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardens on Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>